using BibTeXLibrary;
using BibtexManager;
using BibTexManagerUnitTests;
using DigitalProduction.Http;
using DigitalProduction.Projects;
using Google.Apis.CustomSearchAPI.v1.Data;

namespace BibtexManagerUnitTests
{
	[TestClass]
	public class SpeHttpTests
	{

		/// <summary>
		/// 
		/// </summary>
		[TestMethod]
		public void SearchTest1()
		{
			TestImporter importer = new TestImporter()
			{
				BibEntryStrings = new string[]
				{
					"\t\t\t@proceedings{\r\n\t\t\t\t10.2118/217965-MS,\r\n    author = {Dunn, Joel},\r\n    title = \"{Identifying Cumulative TVD Error in Horizontal Wells Drilled with Rotary Steerable Systems}\",\r\n    volume = {Day 1 Tue, March 05, 2024},\r\n    series = {SPE/IADC Drilling Conference and Exhibition},\r\n    pages = {D011S001R001},\r\n    year = {2024},\r\n    month = {03},\r\n    abstract = \"{It is known that the Stockhausen Effect, characterized as the accumulation of TVD error in directional wellbores resulting from the slide/rotate process employed with bent-housing mud motors, can have a significant impact on wellbore placement in the TVD plane. While much research has been conducted, and commercial solutions have been deployed to account for and correct these errors, all are focused on mud motor slide/rotate drilling. As contemporary drilling programs move to ever-increasing lateral lengths, utilization of Rotary Steerable Systems (RSS) is also trending upward. While potential advantages may exist in favor of RSS, like the elimination of slide drilling, it is important to consider that not all undesirable phenomena associated with slide drilling (well placement error, tortuosity, rugosity, high localized DLS, etc.) vanish from the wellbore. These characteristics are still present in the RSS wellbore and should be analyzed and quantified to ensure that wellbore quality metrics are consistent for all drilling methods.To investigate cumulative TVD error in RSS wells, we developed a system to utilize the real time downhole steering data from RSS to populate a steering sheet that can be processed through an algorithm designed to account for TVD errors resulting from the Stockhausen effect. By capturing the RSS toolface and steering proportion in real time, we can determine at what intervals the RSS is actively steering and during what intervals it is drilling in a neutral, non-biasing mode. The result of cycling between steering and non-steering cycles creates a pattern similar to a slide/rotate sequence experienced when using steerable mud motors. This information allows us to construct a more accurate representation of the true trajectory of the wellbore than is provided by minimum curvature between the standard 95’ survey course lengths. In addition to uncovering TVD error this method also provides a higher resolution picture of various tortuosity metrics like borehole curvature and torsion.We examined data from numerous wells across several basins to observe the TVD error generated by RSS steering mechanisms. It was concluded that these TVD errors should be considered for accurate wellbore positioning, and in addition revealed potential to enhance trajectory optimization capabilities of some Rotary Steerable Systems. In addition to uncovering TVD error, the high-resolution trajectory allows for a thorough examination of wellbore tortuosity, including localized DLS, and wellbore curvature and torsion to aid in identifying potential trouble zones in the lateral.}\",\r\n    doi = {10.2118/217965-MS},\r\n    url = {https://doi.org/10.2118/217965-MS},\r\n    eprint = {https://onepetro.org/SPEDC/proceedings-pdf/24DC/1-24DC/D011S001R001/3381048/spe-217965-ms.pdf},\r\n}"

				}
			};

			ProjectExtractor projectExtractor	= ProjectExtractor.ExtractAndDeserializeProject<BibtexProject>(@"..\..\..\..\Test Files\Test Project.bibproj");
			BibtexProject project				= (BibtexProject)projectExtractor.Project;
		}


		/// <summary>
		/// 
		/// </summary>
		[TestMethod]
		public void SearchTest2()
		{
			CustomSearch.SetCxAndKey(CustomSearchKey.Deserialize(@"..\..\customsearchkey.xml"));


			string search1 = "A Novel Approach To Borehole Quality Measurement In Unconventional Drilling";
			//string search2 = "Proven Well Stabilization Technology for Trouble-Free Drilling and Cost Savings in Pressurized Permeable Formations";
			string searchTerms = search1;

			IList<Result> results = CustomSearch.Search(searchTerms);

			string resultString = "Search: " + searchTerms + Environment.NewLine + Environment.NewLine;
			foreach (Result result in results)
			{
				resultString += ResultString(result) + Environment.NewLine + Environment.NewLine + Environment.NewLine;
			}

			//Assert.AreEqual(Statistics.Covariance(xValues, yValues), 2.9167, 0.0001, errorMessage);
		}

		private string ResultString(Result result)
		{
			string resultString = "";
			resultString += "Title:        " + result.Title + Environment.NewLine;
			resultString += "URL:          " + result.FormattedUrl + Environment.NewLine;
			resultString += "HTML Title:   " + result.HtmlTitle + Environment.NewLine;
			resultString += "Display Link: " + result.DisplayLink + Environment.NewLine;
			resultString += "Link:         " + result.Link + Environment.NewLine;
			resultString += "HtmlSnippet:  " + result.HtmlSnippet + Environment.NewLine;
			resultString += "Snippet:      " + result.Snippet + Environment.NewLine;
			//resultString += ": " + result + Environment.NewLine;
			return resultString;
		}

	} // End class.
} // End namespace.